// https://swiperjs.com/get-started#installation
import '../js/navigation';
import '../js/hero-slider';
import '../js/tours-slider';
import './instructors-slider';
import './gallery-slider';
import './adv-slider';
import './reviews-slider';
import '../js/form';
